### PR TITLE
Merge branch 'master' into develop

### PR DESCRIPTION
**Pull request by walterdolce**
@nnevala @mlopes 
Shall we make `develop` default branch as usual, so that then `master` will contain `release/*`, etc?

img

### CODE REVIEW

**Comment by mlopes** [comment]
I would question the need for a develop branch at all, is there any reason why this shouldn't be continuously delivered as soon as a feature is done?

**Comment by walterdolce** [comment]
The only one that come to my mind is potential bugs found in the implemented feature. 
I'm assuming that after a feature is done we would test it first and see if someone spot any issues.

@nnevala ?

**Comment by mlopes** [comment]
Yes, test it first, and then merge it. The use of "develop" is for integrating features and test a bundle of work (such as a sprint), before putting it in production.
I would also suggest that all features should be split in small enough chunks that the feature branch doesn't live for more than a few days.

**Comment by walterdolce** [comment]
Fine for me about the `develop` branch thing.

> that the feature branch doesn't live for more than a few days

What do you mean?

**Comment by mlopes** [comment]
I mean it should be forked, merged and deleted in a few days.

**Pull request closed without merging**
